### ISSUE TITLE
Add Varnish 4.1.x support

### ISSUE THREAD

**Issue by gongled** [cscart/full-page-cache-addon#1]
Would be great to support not only Varnish 4.0.x but also Varnish 4.1.x and newer versions.

**Comment by alpharder** [comment]
Feel free to submit your pull requests. Currently there are no plans to improve this module in the nearest future..

**Comment by gongled** [comment]
Well, OK can prepare PR for Varnish 4.1.x. But in consideration of issue numbers and your words about module development, I don't see any sense to do something at all.
