### ISSUE TITLE
it doesn't work with https proxy

### ISSUE THREAD

**Issue by isarzhan** [cscart/full-page-cache-addon#11]
Hi, i need to configure this addon for working like back end. But there works redirect from https to http because the setting in cart set. What need i change in cart that it works correctly, set hook 127.0.0.1 in config file of cart to disable https?
Scheme:  Client ->  nginx 443 ->(Varnish, Apache, etc, it doesn't matter) 80 -> (cs-cart shopping cart, rendering content and return back to client).
Thnx.

**Comment by alpharder** [comment]
@isarzhan Sorry for such a late reply. Disabling HTTPS at CS-Cart settings should do the trick. However, CS-Cart will generate HTTP links, so this must be handled using the hook at the `fn_url` function.

**Comment by isarzhan** [comment]
Thanks. i did such.
